version: 1

reviews:
  enabled: true
  summary: true
  suggestions: true
  test_coverage: true
  security: true
  performance: true
  style: true
  max_context: 50
  path_filters:
    include:
      - "backend/**"
      - "frontend/**"
      - "src/**"
      - ".github/**"
      - "scripts/**"
    exclude:
      - "**/node_modules/**"
      - "**/dist/**"
      - "**/.next/**"
      - "**/build/**"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.svg"
      - "**/*.css"
      - "**/*.md"
      - "**/*.lock"
      - "**/*.snap"
      - "**/*.snapshots"
      - "**/*.spec.ts"
      - "**/*.test.ts"
      - "**/e2e/**"

behavior:
  fail_on_errors: false
  approve_when_consistent: true
  enable_status_check: true