version: 1

reviews:
  enabled: true
  summary: true
  explain_changes: true
  max_comments: 50
  path_filters:
    include:
      - "src/**"
      - "frontend/**"
    exclude:
      - "node_modules/**"
      - "dist/**"
      - "build/**"
      - ".next/**"
      - "coverage/**"
      - "backend/**"
      - "onchain/**"
      - "scripts/**"

behavior:
  fail_on_errors: false
  approve_on_no_issues: true
