version: 1
reviews:
  enabled: true
  summary: true
  explain_changes: true
  max_comments: 80
filters:
  paths:
    include:
      - "src/**"
    exclude:
      - "node_modules/**"
      - "dist/**"
      - "build/**"
formatting:
  max_suggestions: 50
  label_non_blocking: "non-blocking"
behavior:
  # Keep reviews informational; do not fail status checks on suggestions.
  fail_on_errors: false
  approve_on_no_issues: true
