version: 1

reviews:
  enabled: true
  summary: true
  explain_changes: true
  max_comments: 100
  severity_threshold: info
  path_filters:
    include:
      - "src/**"
      - "apps/**"
      - "packages/**"
    exclude:
      - "node_modules/**"
      - "dist/**"
      - "build/**"
      - ".next/**"
      - "coverage/**"

formatting:
  max_suggestions: 80
  label_non_blocking: non-blocking

behavior:
  fail_on_errors: false
  approve_on_no_issues: true
  suggest_fixes: true
