version: 1
revision: 3
enabled: true
public_changes: true

reviews:
  enabled: true
  summary: true
  suggestions: true
  test_coverage: true
  security: true
  performance: true
  style: true

path_filters:
  max_contexts: 50
  include:
    - "backend/**"
    - "frontend/**"
    - "src/**"
    - ".github/**"
    - "scripts/**"
    - "README.md"
    - ".eslintrc*"
    - "tsconfig*.json"
  exclude:
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/.next/**"
    - "**/build/**"
    - "**/.turbo/**"
    - "**/coverage/**"
    - "**/public/**"
    - "**/*.png"
    - "**/*.jpg"
    - "**/*.jpeg"
    - "**/*.gif"
    - "**/*.ico"
    - "**/*.svg"
    - "**/*.css"
    - "**/*.scss"
    - "**/*.md"
    - "**/*.lock"
    - "**/*.snap"
    - "**/*.snapshots"
    - "**/*.spec.ts"
    - "**/*.test.ts"
    - "**/*.map"
    - "**/e2e/**"
    - "**/__generated__/**"

behavior:
  fail_on_errors: false
  approve_when_consistent: true

ci:
  enable_status_check: true
